### ISSUE TITLE
Severe Bug - The program fails to start with the command 'pnpm start', urgent fix required

### ISSUE THREAD

**Issue by zongyanbin** [ai16z/eliza#326] opened 2024-11-15 03:44 UTC
**Describe the bug**
The program fails to run at all when following the steps to set it up and execute the commands. After cloning the repository git clone git@github.com:ai16z/eliza.git, and going through the setup process including installing prerequisites like Python 2.7+, Node.js 23.1+, and pnpm, editing the .env file and character file as instructed, and then running the commands pnpm i and pnpm start, the program doesn't start. Tried again with the latest code today but still faced the same issue. It's quite surprising that such a serious problem exists and it seems no one has addressed it yet.

**To Reproduce**
Clone the repository: git clone git@github.com:ai16z/eliza.git
Ensure the following prerequisites are installed:
Python 2.7+
Node.js 23.1+
pnpm
Edit the .env file:
Copy .env.example to .env and fill in the appropriate values.
Edit the TWITTER environment variables to add your bot's username and password.
After setting up the .env file and character file, run the following commands:
pnpm i
pnpm start

**Expected behavior**
Error message
zyb@zybdeMacBook-Pro eliza % pnpm start

> eliza@ start /Users/zyb/project/ai/eliza
> pnpm --filter "@ai16z/agent" start --isRoot

> @ai16z/agent@0.0.1 start /Users/zyb/project/ai/eliza/packages/agent
> node --loader ts-node/esm src/index.ts "--isRoot"

(node:59060) ExperimentalWarning: `--experimental-loader` may be removed in the future; instead use `register()`:
--import 'data:text/javascript,import { register } from "node:module"; import { pathToFileURL } from "node:url"; register("ts-node/esm", pathToFileURL("./"));'
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59060) [DEP0180] DeprecationWarning: fs.Stats constructor is deprecated.
(Use `node --trace-deprecation ...` to show where the warning was created)

node:internal/modules/run_main:122
    triggerUncaughtException(
    ^
[Object: null prototype] {
  [Symbol(nodejs.util.inspect.custom)]: [Function: [nodejs.util.inspect.custom]]
}

Node.js v23.1.0
/Users/zyb/project/ai/eliza/packages/agent:
 ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  @ai16z/agent@0.0.1 start: `node --loader ts-node/esm src/index.ts "--isRoot"`
Exit status 1
 ELIFECYCLE  Command failed with exit code 1.
zyb@zybdeMacBook-Pro eliza % 

**Screenshots**

![aaaa](https://github.com/user-attachments/assets/7db9ced8-b255-4182-bbbb-d5ceb1283300)

**Comment by odilitime** [comment] 2024-11-15 03:47
Try checking out v0.0.10 and running that

**Comment by yodamaster726** [comment] 2024-11-15 04:16
Also curious if ‘pnpm run dev’ works.  I just pulled the code 2 hrs ago and it started for me. I was just iuaing the basic agent though.  Didn’t config twitter.  But good idea to try the tagged version mentioned previously

**Comment by lalalune** [comment] 2024-11-15 10:11
Try pnpm run dev. The problem is start doesn't run tsc. I pushed a fix for this to main.

There is an error in your code, tsc will show what it is

**Comment by lalalune** [comment] 2024-11-15 14:08
I'm closing this because I think it's a bug related to JSON formatting or something, not broken main

**Closed by lalalune** 2024-11-15 14:08 UTC
Labels: bug
