### ISSUE TITLE
Can't Update Character Personality After Modifications in defaultCharacter.ts

### ISSUE THREAD

**Issue by SotoAlt** [ai16z/eliza#95] opened 2024-10-30 12:34 UTC
**Describe the bug**
After modifying the character personality in defaultCharacter.ts, the AI responses remain unchanged and continue using the old personality settings in both Discord and Twitter interactions. However, the Twitter post creation functionality correctly reflects the new personality changes.

**To Reproduce**
1. Navigate to defaultCharacter.ts
2. Modify the character personality settings/prompt
3. Save the changes and restart the application
4. Test interactions on Discord - responses use old personality
5. Test interactions on Twitter - responses use old personality
6. Test Twitter post creation - correctly uses new personality

**Expected behavior**
- When defaultCharacter.ts is modified, all AI interactions (Discord responses, Twitter replies, and Twitter posts) should reflect the new personality settings immediately after application restart.
- The character should consistently maintain the new personality across all platforms and interaction types.

**Screenshots**

**Additional context**
- The inconsistency between Twitter post creation and response behavior suggests a possible caching issue or incomplete personality update propagation across different modules
- The issue persists across application restarts
- Twitter post creation working correctly with new personality indicates that the character file is being read properly in some contexts but not others

**Comment by chochotron** [comment] 2024-10-30 14:17
found a workaround this issue, 
deleting db.sqlite on every change on the character personality/style, restart app, and it works with the updated personality

**Comment by lalalune** [comment] 2024-11-04 05:47
Closing this because I think it's a feature, not a bug. We'll need a script to clear agent memory or something.

**Closed by lalalune** 2024-11-04 05:47 UTC
Labels: bug
